services:
  namix-back:
    build:
      dockerfile: Dockerfile-test
    container_name: namix-back
    environment:
      - TZ=Asia/Yekaterinburg
      - DATABASE_URL=postgresql://postgres:postgres@namix-db:5432/namix
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
    depends_on:
      - database

  database:
    image: postgres
    container_name: namix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: namix
    volumes:
      - namix-db:/var/lib/postgresql/data
    ports:
      - 5438:5432

volumes:
  namix-db:
